[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a704f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c282eb1f28d166afaa1bd35e1f1b44ff/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a73580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c282eb1f28d166afaa1bd35e1f1b44ff/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a70940>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c282eb1f28d166afaa1bd35e1f1b44ff/title